name: Build macOS .app with py2app

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
          pip install -r requirements.txt || true

      - name: Build app
        run: |
          python setup.py py2app

      - name: Archive .app
        run: |
          cd dist
          zip -r Telegram_Parser.zip *.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram_Parser
          path: dist/Telegram_Parser.zip
